# Below are the development and test databases.
# I added the Figaro to secure my password.
# https://github.com/laserlemon/figaro 

development:
  adapter: postgresql
  encoding: unicode
  database: champ_test_development
  pool: 5
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: champ_test_test
  pool: 5
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  timeout: 5000
